### ISSUE TITLE
Need help compiling for Ubuntu 16.04

### ISSUE THREAD

**Issue by Saya47** [notpeter/dante#3]
Hello
The apt repositories are outdated and have 1.1 dante server debs.
I'd like to compile from source and install the software, so far, I have downloaded and extracted the dante 1.4 tar.gz and have done:
`./configure`
`make`
`make check`
`sudo make install`
And when I tried `danted -v` I see it's not installed.
So from the INSTALL readme file, I found out it's installed in `/usr/local`
I tried `. /usr/local/bin/socksify` but I got this error:
`error: parseconfig(): could not open config file /etc/socks.conf`
So I copied the file from `/usr/local/man/man5/socks.conf` to `/etc/socks.conf`
But it returns error on line 1.

I think I'm doing it all wrong then, please help.
I found no service named danted in systemctl.
Thanks very much.

**Comment by Saya47** [comment]
Any help? :)

**Comment by notpeter** [comment]
Hi @Saya47

Sorry I missed this 3.5 years ago but late is better than never.

You were really close. `/usr/local/man/man5/socks.conf` is the manual page describing `socks.conf` while `socks.conf` examples are in the [dante/example](https://github.com/notpeter/dante/tree/main/dante/example) directory.

Best of luck!
