### ISSUE TITLE
Ubuntu 22.04 service crashes by OOM killer

### ISSUE THREAD

**Issue by xahon** [notpeter/dante#5]
When I launched dante-server using configuration mentioned here https://github.com/saaiful/socks5/blob/main/socks5.sh (replacing deprecated `method` with `socksmethod`) on Ubuntu 22.04 it works for some time, then the service crashes due to being OOM-killed, never restarts by itself. The same configuration works fine on Ubuntu 18.04, I had to downgrade my VPS OS to 18.04 in order for it to work without interruptions

**Comment by notpeter** [comment]
This is just a mirror. Not a place for support. See: dante.org.
